using DbForge.WPF.ViewModels.Base;

namespace DbForge.WPF.ViewModels.Compare;

/// <summary>
/// One row in the compare grid. SQL is generated by the parent VM on selection —
/// do NOT store SourceSql/TargetSql here.
/// </summary>
public class CompareRowViewModel : BaseViewModel
{
    public string ObjectType { get; set; } = string.Empty;
    public string TypeIcon { get; set; } = "⊞";
    public string Owner { get; set; } = "dbo";
    public string TargetOwner { get; set; } = "dbo";
    public string SourceObjectName { get; set; } = string.Empty;
    public string TargetObjectName { get; set; } = string.Empty;
    public string ParentName { get; set; } = string.Empty;

    /// <summary>"OnlyInSource" | "OnlyInTarget" | "Different" | "Identical"</summary>
    public string Status { get; set; } = string.Empty;

    public int SortOrder => Status switch
    {
        "OnlyInSource" => 1,
        "Different" => 2,
        "OnlyInTarget" => 3,
        _ => 4
    };

    public string GroupLabel => Status switch
    {
        "OnlyInSource" => "Only in Source",
        "OnlyInTarget" => "Only in Target",
        "Different" => "Different",
        _ => "Identical"
    };

    /// <summary>"Create" | "Update" | "Drop" | "Equal"</summary>
    public string Operation { get; set; } = string.Empty;

    public string OperationSymbol => Operation switch
    {
        "Create" => "→",
        "Update" => "↔",
        "Drop" => "✕",
        _ => "="
    };

    private bool _isChecked = true;
    public bool IsChecked
    {
        get => _isChecked;
        set => Set(ref _isChecked, value);
    }
}